apiVersion: v1
kind: Service
metadata:
  name: stationredisservice 
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.stationredis.port}} 
    name: stationredis
    targetPort: 6379 
    protocol: TCP
  selector:
    app: stationredis
