apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stationfront-hpa
  namespace: {{ .Release.Namespace | quote }}
spec:
  minReplicas: {{ .Values.stationfront.nbReplicas }}
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stationfront-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80