apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stationdb-data 
  namespace: {{ .Release.Namespace | quote }} 
spec:
  storageClassName: {{ .Values.stationdb.storage.storageClass | quote}} 
  accessModes: 
    -  ReadWriteOnce
  resources:
    requests: 
      storage: 3G
  volumeName: station-pv 
