apiVersion: v1
kind: Secret
metadata:
  name: stationredis-secret 
  namespace:  {{ .Release.Namespace | quote }}
type: Opaque
data:
  # Redis password
  redis-password: {{ .Values.stationredis.redisPassword | b64enc | quote }}
