apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stationfrontingress
  namespace: {{ .Release.Namespace | quote }}  
{{- if .Values.stationfront.ingress.annotations }}
  annotations:
{{ toYaml .Values.stationfront.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.stationfront.hostname }}
    http:
      paths:
      - path: /station-angular4-poc
        pathType: Prefix
        backend:
          service:
            name: stationfrontservice
            port:
              number: {{ .Values.stationfront.service.internalPort }}