apiVersion: v1
kind: PersistentVolume
metadata:
  name: station-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.stationdb.storage.storageClass | quote }}
  hostPath:
    path: C:\OpenshiftStorage
    type: DirectoryOrCreate
