apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stationback-route
  namespace: {{ .Release.Namespace | quote }}
spec:
  host: {{ .Values.stationback.hostname }}
  path: /StationDemoSecureWeb 
  to:
    kind: Service
    name: stationbackservice
    weight: 100      # 100% traffic
  port:
    targetPort: stationback
  tls:
    termination: edge                 # OpenShift router handles TLS
    insecureEdgeTerminationPolicy: Redirect  # redirect HTTP -> HTTPS