apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stationfront-route
spec:
  host: {{ .Values.stationfront.hostname }}
  path: /station-angular4-poc
  to:
    kind: Service
    name: stationfrontservice
    weight: 100      # 100% traffic
  port:
    targetPort: stationfrontnginx