apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stationback-ingress
  namespace: {{ .Release.Namespace | quote }}
  
{{- if .Values.stationback.ingress.annotations }}
  annotations:
{{ toYaml .Values.stationback.ingress.annotations | indent 4 }}
{{- end }}
  
spec:
  rules:
  - host: {{ .Values.stationback.hostname }}
    http:
      paths:
      - path: /StationDemoSecureWeb 
        pathType: Prefix
        backend:
          service:
            name: stationbackservice
            port:
              number: {{ .Values.stationback.service.internalPort }}