apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationback-deploy
  namespace: {{station_namespace}}
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  # 2. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  stationback
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: stationback
    spec:
      securityContext:
        runAsUser: 20050
        runAsGroup: 20050
      containers:
        - name: stationback
          image: kagzouli3/station-back:{{station.version}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - all
          env: 
          - name: DB_TRAFSTAT_URL
            value: "jdbc:mysql://stationdbservice.stationdev.svc.cluster.local:3306/StationDemoDb?connectTimeout=0"
          - name: DB_TRAFSTAT_DRIVERCLASS
            value: "com.mysql.jdbc.Driver"
          - name: DB_TRAFSTAT_MAXACTIVE
            value: "15"
          - name: DB_TRAFSTAT_USERNAME
            value: stationUser
          - name: DB_TRAFSTAT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stationdb-secret
                key: database-password
          - name: REDIS_HOSTNAME
            value: stationredisservice.stationdev2.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASS 
            valueFrom:
              secretKeyRef:
                name: stationredis-secret
                key: redis-password
          - name: REDIS_USESSL
            value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 460m
              memory: 768Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /StationDemoSecureWeb/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 17
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /StationDemoSecureWeb/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 17
          ports:
          - containerPort: 8080
            protocol: TCP 
      serviceAccountName: station
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100  
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: stationback
              topologyKey: kubernetes.io/hostname
